### ISSUE TITLE
How to import from a typescript project?

### ISSUE THREAD

**Issue by eoghanmurray** [vnmc/boreas#2]
Hi!

I haven't been able to figure out how to import.
I've installed via yarn/npm in my project

in my typescript project I've tried `import { parse } from 'boreas';`
but I get:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
boreas (imported by src/record/mutation.ts)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
boreas (guessing 'boreas')
```
And the output js expects me to pass in the reference to boreas.

Then I did some digging and tried to alter the `node_modules/boreas/package.json` to add the following:

```
	"main": "./src/parser.ts",
	"types": "./src/types.ts",
```

However, I now get the following error when I try to compile my typescript project:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../../node_modules/boreas/src/parser.ts (5:9)
3: // ==================================================================
4: 
5: import T = require('./types');
```

OK, so maybe main should be a js file:

```
	"main": "./lib/parser.js",
	"types": "./src/types.ts",
```
The above gives:
```
[!] Error: 'parse' is not exported by ../../node_modules/boreas/lib/parser.js, imported by src/record/mutation.ts
```

So I then created a new directory `node_modules/boreas/my` and did the following:

```
esbuild src/*.ts --bundle --format=esm --outdir=my
```
And changed the main entry point to "./my/parser.js"

This actually worked and I was able to import okay.

Could this be supported in some sort of official bundling?

With thanks.

**Comment by matthias-christen** [comment]
I updated the sources to use `import` instead of `require`.
When you update to the latest package, you should be able to directly use imports in your TypeScript project.
Make sure you import from the `src` directory (and not `lib`).
