### ISSUE TITLE
How to tree shake?

### ISSUE THREAD

**Issue by eoghanmurray** [vnmc/boreas#4]
I've imported `parseDeclarations` in order to parse the style attributes of elements.

The style attributes are much more limited and can't e.g. include @media rules or anything, however in the build, classes like `AtCustomMedia` get included.

Is there any way to tree shake these out of the final build?  I'm not familiar with how best to do that or what I should turn on to do so, and maybe it depends on my build process (see the other tickets).

The result is an extra 184K of code which almost doubles the amount of code of [the project ](https://github.com/rrweb-io/rrweb/)that I'm working on which won't be a goer!

**Comment by matthias-christen** [comment]
If you import directly from the `src` folder into your TypeScript project using the v1.0.3 release, your bundler should be able to tree-shake, if you only need `parseDeclarations`.
